name: Up to Date

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run Pytest
        run: |
          pytest tests/

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: report.xml

      - name: Test Status Badge
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = "${{ job.status }}" === "success" ? "passing" : "failing";
            core.setOutput("status", status);
        

      - name: Update Badge
        uses: RubbaBoy/BYOB@v1
        with:
          NAME: Test Status
          LABEL: Pytest
          STATUS: ${{ steps.test_status.outputs.status }}
          COLOR: ${{ steps.test_status.outputs.status == 'passing' && 'green' || 'red' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
